// <auto-generated />
using BackEndApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackEndApi.Migrations
{
    [DbContext(typeof(BackEndApiContext))]
    [Migration("20181121140142_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BackEndApi.Models.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DateMade")
                        .IsRequired();

                    b.Property<string>("PhotoDescription");

                    b.Property<string>("PhotoTitle")
                        .IsRequired();

                    b.Property<string>("PhotoUrl")
                        .IsRequired();

                    b.Property<string>("UserRefId");

                    b.HasKey("PhotoId");

                    b.HasIndex("UserRefId");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("BackEndApi.Models.User", b =>
                {
                    b.Property<string>("UserName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.HasKey("UserName");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BackEndApi.Models.Photo", b =>
                {
                    b.HasOne("BackEndApi.Models.User")
                        .WithMany("Photos")
                        .HasForeignKey("UserRefId");
                });
#pragma warning restore 612, 618
        }
    }
}
